### ISSUE TITLE
init.d unable to start...

### ISSUE THREAD

**Issue by juniwatanabe** [mumblepins/bluz-gateway#13]
Can you tell me how should i do to fix my error as bellow... 
just run 'bluz-gateway' seems fine, but can't run with init.d...

pi@raspi3_1:~ $ sudo /etc/init.d/bluz-gateway start
Starting bluz-gateway
Unable to start, see /var/log/bluz-gateway.log and /var/log/bluz-gateway.err
pi@raspi3_1:~ $ events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::3000
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at Server._listen2 (net.js:1234:14)
    at listen (net.js:1270:10)
    at Server.listen (net.js:1366:5)
    at EventEmitter.listen (/home/pi/.npm-global/lib/node_modules/bluz-gateway/node_modules/express/lib/application.js:617:24)
    at module.exports (/home/pi/.npm-global/lib/node_modules/bluz-gateway/info-server.js:118:23)
    at Object.<anonymous> (/home/pi/.npm-global/lib/node_modules/bluz-gateway/app.js:51:41)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

**Comment by peternoyes** [comment]
I have seen this happen as well. It is not starting because you already have an instance running that is bound to port 3000. What is happening for me is that it fails to run at startup, but still eats the port. It is then impossible to start without changing the config.json to use a different port.
My solution for now is to manually start the server.
